### ISSUE TITLE
New line disappears (on publishing) after pasting text

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Aztec-Android#233] opened 2017-02-08 09:38 UTC
Noticed that the post content is published all on one line, although it was on 2 different lines in the editor.

### Reproduced
1. Start a new post and write something on the first line. Tap `enter`.
2. You're now on the 2nd line of the editor.
3. Paste here a link/text copied  from another app.
4. Publish the post.

If you check the post on the site you can see that the text that was on the 2nd line is now on the first line. Concatenated to the other text.

#### Tested
Nexus 5x on 7.1.1 with Integration branch.

**Comment by khaykov** [comment] 2017-03-16 08:27
This issue was caused by [PostUploadService](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java) stripping `<br>` tags from post on upload.

It's fixed in the dev branch of wpandroid.

**Closed by khaykov** 2017-03-16 08:27 UTC
Labels: bug, high priority
