### ISSUE TITLE
Crash: Deleting Line Before Block Format

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#144] opened 2016-12-13 21:45 UTC
### Expected
When pressing backspace at the beginning of a line following a block format, the line is deleted and the cursor moves to the end of the preceding line.

### Observed
The app crashes.  See the animation and stack trace below for details.

![crash](https://cloud.githubusercontent.com/assets/3827611/21160629/c5ecc140-c142-11e6-9267-bee32cc2bf04.gif)

```
12-13 13:36:14.526 1864-1864/org.wordpress.aztec E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.aztec, PID: 1864
    java.lang.IndexOutOfBoundsException: setSpan (115 ... 114) has end before start
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1258)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
        at org.wordpress.aztec.formatting.BlockFormatter.handleBlockStyling(BlockFormatter.kt:124)
        at org.wordpress.aztec.AztecText.afterTextChanged(AztecText.kt:367)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8203)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10382)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
        at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:251)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:459)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Reproduced
1. Select end of ***Link***.
2. Tap backspace key five times.
3. Notice crash.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by khaykov** [comment] 2016-12-19 04:56
@theck13 Can't reproduce it =\ Does this still happen to you with current version of dev branch?

**Comment by theck13** [comment] 2016-12-19 05:23
I can't reproduce it anymore on my device or emulators.  You can close this for now and we'll reopen if it pops up again.

**Comment by khaykov** [comment] 2016-12-19 05:24
Thanks for checking! Closing.

**Closed by khaykov** 2016-12-19 05:24 UTC
Labels: bug
