### ISSUE TITLE
Cursor Jumps When Deleting Text Before Images on Devices with Nougat

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Aztec-Android#213] opened 2017-01-28 00:11 UTC
### Expected
The cursor remains _after_ text when using backspace to delete text surrounding images.

### Observed
The cursor jumps _before_ text when using backspace to delete text surrounding images.  Note the behavior only occurs on ***devices*** with Nougat.  Testing on emulators with Nougat and devices pre-Nougat do not show this behavior.

### Reproduced
***Before Image***
1. Move cursor immediately _before_ image.
2. Type "text" before image.
3. Notice cursor is between "text" and image.
4. Tap backspace kay.
5. Notice cursor is between "te" and "t" letters.
6. Tap backspace key.
7. Notice cursor is before "et" letters.

***After Image***
1. Move cursor immediately _after_ image.
2. Type "text" after image.
3. Notice cursor is after "text" letters.
4. Tap backspace kay.
5. Notice cursor is between "te" and "t" letters.
6. Tap backspace key.
7. Notice cursor is before "et" letters.

#### Tested
Google Pixel on Android 7.1.1 with AztecDemo 1.0

**Comment by hypest** [comment] 2017-01-28 00:16
It seems that the bug is caused by https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L871-L873. Our code messes up the order of some of the events emitted by the EditText ending up in a `selectionChanged` event before the text-changed events. That causes the cursor to move _and then_ the character be deleted which of course deletes the wrong character.

**Comment by rachelmcr** [comment] 2017-02-16 13:52
I also noticed this happening when I try to delete text in the title field. The cursor moves back one space and then deletes a character, so I can't fully delete the title.

Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35.

**Comment by rachelmcr** [comment] 2017-02-16 14:00
Actually, I am seeing this in both the title and content fields in the editor on my device. I can't delete text normally at all, even if the post content includes only text.

**Comment by zandyring** [comment] 2017-02-17 15:11
I see what Rachel sees as well - If I've written `abc` in the content area and want to delete the `b` I place the cursor between the `b` and the `c` - and the `a` is deleted.
It _sometimes_ seems to "fix" by deleting the return before the word, if it's the first word on a line. But it's inconsistent.
This is without images in the post.
Android 6.0, alpha-35.

**Comment by kraftbj** [comment] 2017-02-21 15:09
Also seen on Pixel XL, Android 7.1.1 (latest pure Android), alpha-35. I have a video if it occurring in the title field if it is helpful.

**Comment by hypest** [comment] 2017-03-06 12:28
FYI, this is fixed with #278 but note, that as of writing, that PR is not merged yet.

**Comment by 0nko** [comment] 2017-03-17 09:36
Fixed by #278.

**Closed by 0nko** 2017-03-17 09:36 UTC
Labels: android version difference, bug, high priority
