### ISSUE TITLE
Crash report alpha-35: OOB in LinkFormatter.getSelectedUrlWithAnchor

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Aztec-Android#265] opened 2017-02-19 07:18 UTC
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:60)
       at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1139)
       at org.wordpress.aztec.AztecText.getSelectedText(AztecText.kt:352)
       at org.wordpress.aztec.formatting.LinkFormatter.getSelectedUrlWithAnchor(LinkFormatter.kt:35)
       at org.wordpress.aztec.AztecText.showLinkDialog(AztecText.kt:831)
       at org.wordpress.aztec.AztecText.showLinkDialog$default(AztecText.kt:830)
       at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:169)
       at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:18)
       at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:96)
       at android.view.View.performClick(View.java:5637)
       at android.widget.CompoundButton.performClick(CompoundButton.java:122)
       at android.view.View$PerformClick.run(View.java:22429)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Pixel C - Android 7.1.1

**Comment by hypest** [comment] 2017-02-24 09:11
Fixed with #272 . Since the PR author wasn't able to reproduce this issue, feel free to reopen if not fixed. Thanks!

**Closed by hypest** 2017-02-24 09:11 UTC
Labels: bug
