### ISSUE TITLE
Horizontal line transforms to HR text on backspace

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Aztec-Android#303] opened 2017-04-05 08:58 UTC
### Expected
Backspacing at the start of a horizontal line should keep the horizontal line.

### Observed
The horizontal line disappears and a "HR" text appears.

### Reproduced
1. Open the demo app with its example text and put the cursor at the beginning of the existing horizontal line
2. Press backspace
3. The horizontal line disappears and a "HR" text appears on the previous line

Screencast:
![screencapture-1491381131748](https://cloud.githubusercontent.com/assets/1032913/24697727/de933d02-19f6-11e7-9adb-f4b38f97782c.gif)

#### Tested
Nexus 5X on Android v7.1.1

**Comment by 0nko** [comment] 2017-04-06 10:02
I can't reproduce this on Pixel running 7.1.2.

**Comment by 0nko** [comment] 2017-04-11 11:19
It's possible the problem has been resolved with #302, but we can't verify it so I'm going to close this issue. Reopen if reported again.

**Closed by 0nko** 2017-04-11 11:19 UTC
Labels: bug, medium priority
